Desarrollar un código en Jupyter Notebook que trabaje con arrays y realice varias operaciones matemáticas y de manipulación de datos.

El programa debe obtener la mediana, el promedio, y las
posiciones de los valores máximo y mínimo de un array. Además, deberá transformar el array en una matriz y utilizar las funciones específicas para ello. A continuación se detalla los requerimientos:


A. Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos del 1 al 10. Este array no debe ser aleatorio.

B. Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores deben ser enteros entre el 1 al 20.

C. Obtener un vector único de 10 elementos, sumando los dos arrays anteriores.

D. Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV.

E. Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando las funciones vistas en la Unidad IV. Tomar el vector de la letra D.

E. Transformar el vector obtenido en una Matriz de 2 x 5


In [2]:
import numpy as np

In [3]:
import random as rd

A. Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos del 1 al 10. Este array no debe ser aleatorio.

In [5]:
array1 = np.arange(1, 11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

B. Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores deben ser enteros entre el 1 al 20.

In [7]:
array2 = np.random.randint(1, 21, size=10)
array2

array([17, 10,  6,  1,  7,  4, 13, 16, 11, 12])

C. Obtener un vector único de 10 elementos, sumando los dos arrays anteriores.

In [8]:
vector= array1 + array2
vector

array([18, 12,  9,  5, 12, 10, 20, 24, 20, 22])

D. Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV.

In [9]:
np.random.shuffle(vector)
vector

array([24, 20,  5, 12, 12, 22, 10, 20, 18,  9])

E. Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando las funciones vistas en la Unidad IV. Tomar el vector de la letra D.

In [10]:
mediana = np.median(vector)
mediana

15.0

In [11]:
promedio = np.mean(vector)
promedio

15.2

In [13]:
valormaximo = np.max(vector)
valormaximo

24

In [15]:
valorminimo = np.min(vector)
valorminimo

5

F. Transformar el vector obtenido en una Matriz de 2 x 5

In [16]:
matirz = vector.reshape(2, 5)
matirz

array([[24, 20,  5, 12, 12],
       [22, 10, 20, 18,  9]])