Importando libreria Numpy

In [ ]:
import numpy as np

Creando una lista de 10 elementos

In [ ]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Transformar lista a un Array

In [ ]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando el tipo de Estructura

In [ ]:
type(arreglo)

numpy.ndarray

Corroborando el tipo de datos del arreglo

In [ ]:
arreglo.dtype

dtype('int64')

Definiendo el Array de int64 a float 64

In [ ]:
np.array(arreglo, dtype = np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Sigue siendo un array de int 64

In [ ]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Transformando de int64 a float64

In [ ]:
arreglo.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Tambien existe una funcion similar a Range pero ocupando Arrays

In [ ]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Arreglo de 2 en 2 utilixando Arange

In [ ]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4><font color = 'aquamarine'><b>Funciones de Numpy</b>></h4>

In [ ]:
print("\033[91mAlgunas Funciones de Numpy\033[00m")

Algunas Funciones de Numpy


<h3><font color = 'Red'><b>Sacando el promedio</b>></h3>

In [ ]:
promedio = np.mean(arreglo)
promedio

5.5

Obteniendo la mediana del Array

In [ ]:
mediana = np.median(arreglo)
mediana

5.5

Desviacion Estandar del Arreglo

In [ ]:
desviacion = np.std(arreglo)
desviacion

2.8722813232690143

Generacion de 10 elementos de solo unos

In [ ]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Generacion de 10 elementos de solo ceros

In [ ]:
arreglo_de_ceros = np.zeros(10)
arreglo_de_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Transformando el arreglo de unos de punto flotante a enteros

In [ ]:
arreglo_int_ones = arreglo_de_unos.astype(np.int64)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Utilizando la funcion Random

Generando arreglo aleatorio de 5 elementos

In [ ]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.48444743, 0.02388474, 0.0551406 , 0.95076289, 0.82534684])

Generando una matris aleatoria de 3x3

In [ ]:
matriz = np.random.rand(3,3)
matriz

array([[0.37260538, 0.74727825, 0.21740772],
       [0.09244183, 0.13881715, 0.51477283],
       [0.44301874, 0.45944131, 0.5087756 ]])

Generando un arreglo aleatorio de 10 numeros enteros del 1 al 1000

In [ ]:
arreglo_aleatorio2= np.random.randint(1,1001,10)
arreglo_aleatorio2

array([386,  72,  93, 661, 985, 603, 570, 538, 763, 271])

Generando una matriz aleatoria de 10 numeros enteros del 1 al 100

In [ ]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 37,  44,  84,  63,  82,  27,  63,   2,  14, 100],
       [ 11,  78,  70,  74,  15,  98,  81,  86,  13,  84],
       [ 35,  96,  61,   5,  87,  18,  75,   5,  86,  77],
       [ 72,  13,   8,  36,  93,  65,  69,   4,  29,  56],
       [ 31,  79,  96,  19,  64,  51,  67,  98,  81,  40],
       [ 36,  64,  77,  50,  90,  37,   9,  67,  17,   4],
       [ 69,  25,   8,  18,  52,  98,  94,  67,  71,  34],
       [ 63,  66,  93,  77,  72,  42,  90,  66,  92,  49],
       [ 45,  16,  55,  37,  12,  54,  13,  67,   4,  98],
       [ 23,  65,  25,  99,  48,  93,  65, 100,  61,  23]])