In [ ]:
import numpy as np

Generando un Array de 12 elementos enteros con Random

In [ ]:
vector = np.arange(1,13)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Obtener la dimension de arreglo

In [ ]:
np.shape(vector)

(12,)

Transformando del vector de 12 elementos a Matriz 4x3 con Reshape

In [ ]:
matriz = vector.reshape(3,4)
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Transformacion del vector de 12 elementos a Matriz 4x3 con Reshape

In [ ]:
np.shape(matriz)

(3, 4)

Otra tranformacion del vector de 9 elementos a Matriz 3x4 con Reshape

In [ ]:
matriz = vector.reshape(4,3)
matriz

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Creando un Tensor

In [ ]:
t = [[[[1, 2, 3],[4, 5, 6],[7, 8, 9],[1, 2, 3]]]]
print(t)

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]


In [ ]:
np.shape(t)

(1, 1, 4, 3)

In [ ]:
dimension = np.shape(t)

np.mean(dimension)
dimension


(1, 1, 4, 3)

Graficando el Vector generado Anteriormente